# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

# if you use bundler
require 'bundler'
Bundler.require

# if you are not using bundler
# require 'rubygems'
# require 'ib'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'IBSample'
end
