# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.

require 'ib'

module Motion
  module Project
    class Config
      attr_reader :files
      attr_reader :resources_dirs

      def initialize(platform = :ios)
        @platform = platform
        @files = []
        @resources_dirs = ['resources']
      end

      def deploy_platform
        @platform == :ios ? 'iPhoneOS' : 'MacOSX'
      end
    end

    class App
      class << self
        attr_writer :config

        def config
          @config ||= Config.new
        end
      end
    end
  end
end

# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
end
